### ISSUE TITLE
Error when try to Load Settings.

### ISSUE THREAD

**Issue by MegaMind-png** [Pullusb/SceneSettings#2]
Hello :) I have been looking for something similar for a blender for a long time, since changing parameters for each scene is very inconvenient every time. Your addon interested me. As far as I understand, the latest version should be suitable for blender 3+. I'm working with blender 3.6.1 and I get the following error when I try to load settings. Could you take the time and tell me what this might be connected with and how to solve it? Thank you :)

Python: Traceback (most recent call last):
   File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\scene_settings-master\operators.py", line 42, in execute
     applySettings(outfile)
   File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\scene_settings-master\functions\functions.py", line 106, in applySettings
     apply_from_dict(loadedSettings)
   File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\scene_settings-master\functions\functions.py", line 96, in apply_from_dict
     setattr(eval(root), attr, value)
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'NoneType'

**Comment by Pullusb** [comment]
Hi,
I tested quickly and I do not have that kind of issue...
But I've just pushed an update (0.3.0) with changes that might fix your problem
Let me know if you still have one.

While I was on it, I also changed a few things and now the compare button pops-up a panel to selectively change the difference from source (instead of just printing in console). This allow for more precise setup instead of blind batch apply scene properties.

Be mindfull that some area are left untouched (like viewlayer settings for example), so I hope it will satisfy your usecase
Also, I did not maintain this addon a lot... a big part of it is still super old code ^^. so bug can still happen.

S.

**Comment by MegaMind-png** [comment]
unfortunately I keep getting the error:
Python: Traceback (most recent call last):
   File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\scene_settings-master\operators.py", line 42, in execute
    
   File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\scene_settings-master\functions\functions.py", line 106, in applySettings
     setattr(eval(root), attr, value)
   File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\scene_settings-master\functions\functions.py", line 96, in apply_from_dict
     print(f'apply {attr}, {value}')
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'NoneType'

**Comment by MegaMind-png** [comment]
In fact, I don't use blender, but upbge (a fork of blender with the BGE game engine). But I don’t think that’s the problem, since essentially it’s the same blender just with a built-in BGE engine

**Comment by Pullusb** [comment]
Ok !

Yes, I saw the use of upbge from your path. I don't think it's the source of the problem as well, but it's not totally excluded either. You should try with a classic blender release 

When do you get the error ? On saving settings ? loading settings ?

In console just above the error can you see what properties it tries to apply ? (enable debug mode in addon preferences just in case)

Can you send a blend with your problematic scene ? Since it only concern the scene settings, you can remove all object in that blend, that way you're not sharing anything personal.

I probably won't have time to check until later this week, but it's much easier to debug if I can have the file and debug the error myself.

**Comment by MegaMind-png** [comment]
I get this error when I try to load scene settings. I don’t think there’s any point in sending you a blend file since I’m testing this addon in the default scene, so there’s nothing superfluous or changed in it :)

**Comment by MegaMind-png** [comment]
Oh, wait, i reload UPBGE and try one more time. Now i get new error in python console and strange result:
Python: Traceback (most recent call last):
  File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\magic_uv\op\uv_sculpt.py", line 465, in modal
    self.__stroke_init(context, event)
  File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\magic_uv\op\uv_sculpt.py", line 253, in __stroke_init
    bm = bmesh.from_edit_mesh(obj.data)
ValueError: The mesh must be in editmode
![image](https://github.com/Pullusb/scene_settings/assets/95245166/78183b8c-fde4-47b6-ab4f-fd972117aff5)

**Comment by MegaMind-png** [comment]
After loading the settings, I get an error and for some reason this texture appears on my screen :) This is a texture from some addon pbr painter or bpainter

**Comment by MegaMind-png** [comment]
That what i get in main console:
Traceback (most recent call last):
  File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\magic_uv\op\uv_sculpt.py", line 465, in modal
    self.__stroke_init(context, event)
  File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\magic_uv\op\uv_sculpt.py", line 253, in __stroke_init
    bm = bmesh.from_edit_mesh(obj.data)
ValueError: The mesh must be in editmode
╨Ю╤И╨╕╨▒╨║╨░: Python: Traceback (most recent call last):
  File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\magic_uv\op\uv_sculpt.py", line 465, in modal
    self.__stroke_init(context, event)
  File "C:\Program Files\Programs\Blenders\UPBGE 0.36.1 Alpha\upbge-0.36.1-windows-x86_64\3.6\scripts\addons\magic_uv\op\uv_sculpt.py", line 253, in __stroke_init
    bm = bmesh.from_edit_mesh(obj.data)
ValueError: The mesh must be in editmode

**Comment by MegaMind-png** [comment]
I think the problem is with some addons

**Comment by MegaMind-png** [comment]
In any case, thanks for your answer. I don't want to waste your time, so don't worry. I'll try to make my own addon for saving and loading scene data

**Comment by Pullusb** [comment]
Indeed it seems the problem comes from the addon trying to set an some addon properties. (besause it check properties recursively from `bpy.context.scene`)

Just in case I tried in upbge vanilla and the was no problems.
It's not that easy to make an exclusion system to avoid crawling in the addons properties. I have an ideas to fix that but do not have the time at the moment.

Well, you seem motivated. good luck with your own implementation then ;)

**Comment by MegaMind-png** [comment]
Did I understand correctly that you automated the retrieval of values? I mean, didn't you manually add each option to save?

**Comment by Pullusb** [comment]
Correct ! Oh I did not add those manually ! That would be way too bothersome, and you would have to update the list on any changes in new blender version !

I just specify a root section, and it crawl on it's properties recursively (but apparently some other addons properties do not like that ^^)

Currently those are the root settings to extract/load at the moment:

`bpy.context.scene`
`bpy.context.scene.render`
`bpy.context.scene.cycles`
`bpy.context.scene.eevee`

Here `context.scene` contains also other enabled addons properties, hence the error.

What I could do (later) is expose the root sections parameters so user might customize what he want to dump in json file.
But it's better to avoid addons props altogether (but again, not easy to do).

Now I pre-apologize if my answer delay becomes very long in future exchanges 😅

**Comment by MegaMind-png** [comment]
Yes, after trying to automate this I ran into the same problem :) If I add the values manually everything works as it should, however it is tedious and in case of changes in future versions of blender it may cause a problem

**Comment by MegaMind-png** [comment]
If you manage to implement this, it will be cool! Unfortunately my knowledge is not enough. I can't make it better than it is now (just add parameters manually).
It's strange that blender developers won't provide such a function. It is very inconvenient when you need to work with another scene in which the parameters have been completely changed or knocked down.
